<#
.SYNOPSIS
    Run Last

.DESCRIPTION
	Part of the PineGuard PowerShell toolchain.
	Re-runs the last requested test command. Edit the parameters below to change the target.

.PARAMETER Project
	Path to a specific test project file (.csproj). Defaults to running all unit tests.

.PARAMETER Filter
	Filter expression for running selective tests (e.g. "FullyQualifiedName~Tests").
#>

# This file is automatically generated by the agent to run the latest requested test command.
# It is intended to be whitelisted in agent settings via wildcard: tools/code-inspection/auto/*.ps1

param(
    [string] $Project,
    [string] $Filter
)

$ErrorActionPreference = "Stop"

Write-Host "Cleaning previous build artifacts..."
dotnet clean --verbosity quiet

Write-Host "Executing last requested test command..."

$testArgs = @()
if ($Project) { $testArgs += @('-Project', $Project) }
if ($Filter) { $testArgs += @('-Filter', $Filter) }

# Forward to the robust test runner
& "$PSScriptRoot/../../testing/Run-Tests.ps1" @testArgs
