<#
.SYNOPSIS
    Run Coverage

.DESCRIPTION
	Part of the PineGuard PowerShell toolchain.

.PARAMETER Scope
	The coverage scope to run. Valid values: Core, MustClauses, GuardClauses, DataAnnotations, FluentValidation, All, Testing.

.PARAMETER Filter
	See the param block for details.
#>

# This file is automatically generated by the agent to run coverage via the whitelisted path.
# It is intended to be whitelisted in agent settings via wildcard: tools/code-inspection/auto/*.ps1

param(
    [ValidateSet('Core', 'MustClauses', 'GuardClauses', 'DataAnnotations', 'FluentValidation', 'All', 'Testing')]
    [string] $Scope = 'All',
    [string] $Filter
)

$ErrorActionPreference = "Stop"

Write-Host "Executing $Scope Code Coverage..."

# Forward to the main coverage script with valid parameters
& "$PSScriptRoot/../../code-coverage/Run-CodeCoverage.ps1" -Scope $Scope -Clean -Filter $Filter
