// <auto-generated />
// This file was generated from ISO 639 language code data.
// Do NOT edit manually.
// Regenerate using ./.iso/GenerateIsoLanguages.ps1
using System;
using System.Collections.Frozen;

namespace PineGuard.Iso.Languages;

/// <summary>
/// ISO 639 language code data.
/// Data source: https://www.iso.org/iso-639-language-codes.html
/// Last updated: 2024-12
/// </summary>
internal static class DefaultIsoLanguageData
{
    internal static readonly FrozenDictionary<string, IsoLanguage> LanguagesByCodeAlpha2;
    internal static readonly FrozenDictionary<string, IsoLanguage> LanguagesByCodeAlpha3;

    static DefaultIsoLanguageData()
    {
        var languages = new[]
        {
<< LANGUAGE_ROWS >>
        };

        LanguagesByCodeAlpha2 = languages.ToFrozenDictionary(
            l => l.Alpha2Code,
            StringComparer.OrdinalIgnoreCase);

        LanguagesByCodeAlpha3 = languages.ToFrozenDictionary(
            l => l.Alpha3Code,
            StringComparer.OrdinalIgnoreCase);
    }
}
