<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsTestProject>false</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="PineGuard.Testing.UnitTests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\PineGuard.Core\PineGuard.Core.csproj" />
  </ItemGroup>

</Project>
