// <auto-generated />
// This file was generated from ISO 4217 currency code data.
// Do NOT edit manually.
// Regenerate using ./.iso/GenerateIsoCurrencies.ps1
using System;
using System.Collections.Frozen;

namespace PineGuard.Iso.Currencies;

/// <summary>
/// ISO 4217 currency code data.
/// Data source: https://www.iso.org/iso-4217-currency-codes.html
/// Last updated: 2024-12
/// </summary>
internal static class DefaultIsoCurrencyData
{
    internal static readonly FrozenDictionary<string, IsoCurrency> CurrenciesByCodeAlpha3;
    internal static readonly FrozenDictionary<string, IsoCurrency> CurrenciesByCodeNumeric;

    static DefaultIsoCurrencyData()
    {
        var currencies = new[]
        {
<< CURRENCY_ROWS >>
        };

        CurrenciesByCodeAlpha3 = currencies.ToFrozenDictionary(
            c => c.Alpha3Code,
            StringComparer.OrdinalIgnoreCase);

        CurrenciesByCodeNumeric = currencies.ToFrozenDictionary(
            c => c.NumericCode,
            StringComparer.Ordinal);
    }
}
