// <auto-generated />
// This file was generated from ISO 3166-1 country code data.
// Do NOT edit manually.
// Regenerate using ./etc/powershell/iso/GenerateIsoCountries.ps1
using System;
using System.Collections.Frozen;

namespace PineGuard.Iso.Countries;

/// <summary>
/// ISO 3166-1 country code data.
/// Data source: https://www.iso.org/iso-3166-country-codes.html
/// Last updated: 2024-12
/// </summary>
internal static class DefaultIsoCountryData
{
    internal static readonly FrozenDictionary<string, IsoCountry> CountriesByCodeAlpha2;
    internal static readonly FrozenDictionary<string, IsoCountry> CountriesByCodeAlpha3;
    internal static readonly FrozenDictionary<string, IsoCountry> CountriesByCodeNumeric;

    static DefaultIsoCountryData()
    {
        var countries = new[]
        {
<< COUNTRY_ROWS >>
        };

        CountriesByCodeAlpha2 = countries.ToFrozenDictionary(
            c => c.Alpha2Code,
            StringComparer.OrdinalIgnoreCase);

        CountriesByCodeAlpha3 = countries.ToFrozenDictionary(
            c => c.Alpha3Code,
            StringComparer.OrdinalIgnoreCase);

        CountriesByCodeNumeric = countries.ToFrozenDictionary(
            c => c.NumericCode,
            StringComparer.Ordinal);
    }
}