// <auto-generated />
// This file was generated from IANA tzdb zone1970.tab.
// Do NOT edit manually.
// Regenerate using ./.iana/GenerateIanaTimeZones.ps1
using PineGuard.Iana.TimeZones;
using System;
using System.Collections.Frozen;
using System.Collections.Generic;

namespace PineGuard.Iana.TimeZones;

/// <summary>
/// IANA tzdb time zone data.
/// Data source: IANA Time Zone Database (tzdb), zone1970.tab
/// </summary>
internal static class DefaultIanaTimeZoneData
{
    internal static readonly FrozenDictionary<string, IanaTimeZone> ZonesById;
    internal static readonly FrozenDictionary<string, FrozenSet<string>> ZoneIdsByCountryAlpha2;

    static DefaultIanaTimeZoneData()
    {
        var zones = new[]
        {
<< TIME_ZONE_ROWS >>
        };

        ZonesById = zones.ToFrozenDictionary(
            z => z.Id,
            StringComparer.Ordinal);

        var map = new Dictionary<string, HashSet<string>>(StringComparer.OrdinalIgnoreCase);

        foreach (var zone in zones)
        {
            foreach (var country in zone.CountryAlpha2Codes)
            {
                if (!map.TryGetValue(country, out var set))
                {
                    set = new HashSet<string>(StringComparer.Ordinal);
                    map[country] = set;
                }

                set.Add(zone.Id);
            }
        }

        ZoneIdsByCountryAlpha2 = map.ToFrozenDictionary(
            kvp => kvp.Key,
            kvp => kvp.Value.ToFrozenSet(StringComparer.Ordinal),
            StringComparer.OrdinalIgnoreCase);
    }
}
