// <auto-generated />
// This file was generated from CLDR supplemental data (windowsZones.xml).
// Do NOT edit manually.
// Regenerate using ./.cldr/GenerateCldrWindowsTimeZones.ps1
using PineGuard.Cldr.TimeZones;
using System;
using System.Collections.Frozen;
using System.Collections.Generic;

namespace PineGuard.Cldr.TimeZones;

/// <summary>
/// CLDR Windows time zone mapping data.
/// Data source: CLDR supplemental/windowsZones.xml
/// </summary>
internal static class DefaultCldrWindowsTimeZoneData
{
    /// <summary>
    /// Windows time zone ID -> (Territory -> IANA time zone IDs)
    /// </summary>
    internal static readonly FrozenDictionary<string, FrozenDictionary<string, string[]>> IanaTimeZoneIdsByWindowsId;

    static DefaultCldrWindowsTimeZoneData()
    {
        var mappings = new[]
        {
<< WINDOWS_ZONE_ROWS >>
        };

        var outer = new Dictionary<string, Dictionary<string, string[]>>(StringComparer.OrdinalIgnoreCase);

        foreach (var m in mappings)
        {
            if (!outer.TryGetValue(m.WindowsId, out var inner))
            {
                inner = new Dictionary<string, string[]>(StringComparer.OrdinalIgnoreCase);
                outer[m.WindowsId] = inner;
            }

            inner[m.Territory] = m.IanaTimeZoneIds;
        }

        IanaTimeZoneIdsByWindowsId = outer.ToFrozenDictionary(
            kvp => kvp.Key,
            kvp => kvp.Value.ToFrozenDictionary(i => i.Key, i => i.Value, StringComparer.OrdinalIgnoreCase),
            StringComparer.OrdinalIgnoreCase);
    }
}
