version: "1.0"

linter: qodana-dotnet

profile:
  name: qodana.recommended

dotnet:
  solution: tools/code-inspection/qodana/PineGuard.Core.Qodana.slnx

bootstrap: dotnet build tools/code-inspection/qodana/PineGuard.Core.Qodana.slnx -c Release

exclude:
  - name: InconsistentNaming
    paths:
      - src/PineGuard.Core/Polyfills/IsExternalInit.cs
  - name: CheckNamespace
    paths:
      - src/PineGuard.Core/Polyfills/IsExternalInit.cs

