<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>PineGuard</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="PineGuard.Core.UnitTests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.ComponentModel.Annotations" />
    <PackageReference Include="System.Text.Json" />
  </ItemGroup>

</Project>
